name: Mojank
main: cc.funkemunky.fixer.Mojank
<<<<<<< HEAD
author: funkemunky
version: 0.0.1
=======
version: 1.1-b1
author: funkemunky
softdepend: [ProtocolLib]
>>>>>>> 6dfd4c36e27508f96a9a7ff4d9ddf83d507eb43a
